### ISSUE TITLE
[Feature request] Support for Android 4.0.4

### ISSUE THREAD

**Issue by tbjorheim** [TeamNewPipe/NewPipe-legacy#2]
Hi. As far as I can understand, the NewPipe-legacy requires Android 4.1. Is it possible to make it work on Android 4.0.4 as well?

**Comment by friendlyanon** [comment]
Since my own phone has JellyBean, I didn't want to go that low on the version list, because it's hard to guarantee the usability that way.  
It's entirely possible to go that low for now, since there were not substantial changes made to the application yet.  
Additionally, the "old player" was entirely pruned from the application in https://github.com/TeamNewPipe/NewPipe/pull/2129 and I am not quite sure of the consequences yet, since NewPipe has been working fine on my 4.3 device, it might have had relevance for OS versions older than JellyBean, but since I can't test that on a physical device, I would prefer to refrain from supporting that.

I'm also just familiarizing myself with the codebase and Android development in general, but I'll do my best to do the appropriate research on the topic of this "old payer" and when deemed irrelevant, I will definitely start supporting IceCreamSandwich.

**Comment by tbjorheim** [comment]
I have used NewPipe on my Samsung Galaxy Tab 8.9 with Android 4.0.4 until version 15 of NewPipe, when support for 4.0.3 - 4.3 was dropped. And it has worked very well, but since Youtube changed something, the old 14.2 version is not working anymore.

I'm not a coder myself, but will gladly help with testing new versions on my tablet with Android 4.0.4. 

Youtube/Google has also recently blocked the stock Youtube app on 4.0.4 and it now only shows a message that you have to upgrade. But that's not possible on Android 4.0.4. And I have read on many forums about people that are very unhappy about this. Many still have phones and tablets which still works very well, and I think it's bad that they need to be trashed just because Youtube/Google decide they are to old.

**Comment by vad1m** [comment]
Would be great to have support for devices with android 4.0.4, please don't drop them.

**Comment by tbjorheim** [comment]
Hi. Any news on support for 4.0.4?

I compile my own version for now using Android Studio and follow the instructions from johnb-xp in this post https://github.com/TeamNewPipe/NewPipe/issues/2033 but selecting minAPI 15 which is for Android 4.0.4.

It works great except the internal videoplayer doesn't work. But have selected external player and open in either VLC, X-plore file manager video player or Dolphin web browser video player. The last two works best.

But I'm only able to get the debug version to work. I'm not familiar at all with developing Android apps, but manage to do just this to make NewPipe work on my tablet. :)

If anyone else still need a version for 4.0.4, please let me know, and I can put the debug version I compile up for download somewhere.

**Comment by ale5000-git** [comment]
@friendlyanon: I also would like to have this support and going even lower if possible.
I can't test it right now but I will be able to do it in the future.

**Comment by timoteo7** [comment]
The Minimun API level is 16 (Android 4.1) ??

I am using Cyanogenmod Optimus Nexus Me

`$ adb shell getprop ro.build.version.release`
> 4.4

but :

`$ adb shell getprop ro.build.version.sdk`
> 10

can the legacy version be more legacy until API level 10 ?

**Comment by tbjorheim** [comment]
Hi again. Has anyone be able to compile v0.18.2 for Android 4.0.4 (API 15)?

I tried, but it seems like exoPlayer need API 16. Is it possible to compile without the player, to use an external player instead?

**Comment by gillhash** [comment]
@tbjorheim it seems friendlyanon has plans to keep support for API 15 alive.

Check this comment  https://github.com/TeamNewPipe/NewPipe-legacy/pull/12#r33953139
 in #12

**Comment by Kovaelin** [comment]
I'm not sure if I should open a new issue, but I'd also like to have this on my old Motorola Xoom, which only has 4.0.3.

**Comment by gillhash** [comment]
@friendlyanon @tbjorheim many people are  demanding support for 4.0.x devices. Would NewPipe Legacy will be made available for old devices running on icecream sandwich ?

By the way Main NewPipe has been updated today to 0.18.4 Besides quashing many bugs it also  includes @blackbox87 downloads fix (PR #21 ) which is yet to be merged in legacy version.

..Can we expect a new legacy update soon ?

**Comment by malekairmaroc7** [comment]
@Kovaelin 
I would like that version as well ...

**Comment by malekairmaroc7** [comment]
Is there a working version for Android 4.0.3?

**Comment by sh000gun** [comment]
Here is the working version for Android 4.0.3 based on 0.19.2 source. Change log:
1. Disable Resolution spinner (only API 15)
2. Disable popup video
3. Add old player again to support very old device like my KFHD 7 Tate

Of course, no malicious code anymore

[Newpiple_0.19.2_minAPI15.apk.zip](https://github.com/TeamNewPipe/NewPipe-legacy/files/4498575/Newpiple_0.19.2_minAPI15.apk.zip)

**Comment by friendlyanon** [comment]
@sh000gun I appreciate your enthusiasm for something I myself don't really have time for due to uni, but please avoid distributing binary blobs like this.  
I'm also pretty sure binary distribution without source code provided is in violation of the GNU General Public License.  
I'd be more than happy to accept a Pull Request if you can make one however.

**Comment by malekairmaroc7** [comment]
@sh000gun Thank you much for the effort you've done! I installed the app on 4.0.3 and it works except the video player. There is just a black screen. Any Idea why?

**Comment by sh000gun** [comment]
@malekairmaroc7 maybe the video player can't play the specific video resolution. I set default resolution 360p in the Setting-->Video & audio and mostly it work all the time

**Comment by malekairmaroc7** [comment]
Well, seems a video player issue then. I even can't play live stream in 360p

**Comment by sh000gun** [comment]
@malekairmaroc7 Here is my latest version that fix Resolution Spinner so you can choose it to play

You can download at: https://drive.google.com/open?id=1_9roWosYM_sf-idB8wJ3ELUJjW-Px2WO

**Comment by malekairmaroc7** [comment]
Thank you for the effort! It still doesn't work either. Now, I don't know where the problem is. The Android TV Box supports up to 1080p. When I choose something higher than 360p it says "Video couldn't load" or just a black screen...

**Comment by sh000gun** [comment]
The problems is Newpipe old player limitation. I think it only plays 720p and 1080, live stream is another topic like this discussion https://github.com/TeamNewPipe/NewPipe/issues/517. 

 You can play 1080p with external player option turn on (with VLC) and of course it will not have audio by current Newpipe implementation. Another stupid workaround is using 2 external players parallel: one running audio stream by clicking background and other one for video playback the same time :)

**Comment by malekairmaroc7** [comment]
I see. I tried using MX Player (VLC doesn't run well), but still same issue here.
Thank you for replying!

**Comment by DavidAntonin** [comment]
Thank you very much for your hard work. Can you release 0.19.03 with youtube music suppor and minimal API 17 (Android 4.2.2) Thank you

**Comment by sh000gun** [comment]
@malekairmaroc7 this version is based on libVLC with most Newpipe functionalities and of course there are bugs :) Hope this help your Android box
https://drive.google.com/file/d/1xncZs__eW6ipnU-ZmbOtmNDar9LJbvyi/view?usp=sharing

**Comment by malekairmaroc7** [comment]
Thank you much for the effort! I'll try It out :)!

Am Freitag, 15. Mai 2020 schrieb sh000gun <notifications@github.com>:

**Comment by malekairmaroc7** [comment]
@sh000gun 
Thank you!!

Unfortunately I run into a guru meditation error when starting a video

**Comment by TobiGr** [comment]
@sh000gun **_Thank you_** for working on the legacy version. If you want, I can add you as collaborator to this repository, so we can ship your changes to everyone using F-Droid. But please **_do not_** upload binaries to google drive (or somewhere else) without sharing its source, too.

**Comment by Kovaelin** [comment]
@sh000gun Thanks for all the work on the legacy version!

Even though there are methods for old devices to run custom ROMs that are more up to date, it's very nice to have support for previous official Android versions that were tablet-centric, and not just scaled up phone versions.

**Comment by sh000gun** [comment]
Hi friend,

This is in development version

https://drive.google.com/file/d/1dg9eszPU0WOHFQpb15uPhFDiW_eQ4_dN/view?usp=sharing

Please let me know the issue

Best,

Shogun

**Comment by sh000gun** [comment]
I am in porting Newpipe for 4.0.3 up with VLC player. If you guys want a testing version, please let me know at nguyendnv@gmail.com

**Comment by tbjorheim** [comment]
@sh000gun Thanks a lot for making a fork working on Android 4.0.x

Works great on my Android 4.0.4 tablet (API 15). The only issue I have noticed so far is that there is some lag when starting a video using the build in video player. The sound starts first, and after a few seconds the picture/video is shown. Same happens if I skip to another place in the video. Maybe the VLC player is a bit to demanding for my tablet, Samsung Galaxy P7320 (same as P7300 but with LTE/4G).

In fact, the same happens if I use VLC as external player. (Version 3.0.13 which is the latest available for Android 4.0.4)

But I been using external player with the video player from the X-plore file manager, and that has been working very well. It starts fast, and no lag.

So thanks again @sh000gun and hope you will keep your fork up to date when newer Newpipe version is released. At least when there is issues due to Youtube changes makes video unable to play. I'm not very interested in a lot of new fancy features, I just want to be able to watch Youtube on my tablet. :) And since the official Youtube app is no longer avaiable, Newpipe is the best option.

**Comment by malekairmaroc7** [comment]
> @sh000gun Thanks a lot for making a fork working on Android 4.0.x
> 
> Works great on my Android 4.0.4 tablet (API 15). The only issue I have noticed so far is that there is some lag when starting a video using the build in video player. The sound starts first, and after a few seconds the picture/video is shown. Same happens if I skip to another place in the video. Maybe the VLC player is a bit to demanding for my tablet, Samsung Galaxy P7320 (same as P7300 but with LTE/4G).
> 
That's my issue as well. VLC is too heavy for my device. MX Player works good on it. @sh000gun Can you update it to MX Player in any way? The HD Streams load at least but I only hear the sound. The picture doesn't react and is lagging :/ . Thank you for the effort so far!!

**Comment by sh000gun** [comment]
> > @sh000gun Thanks a lot for making a fork working on Android 4.0.x
> > Works great on my Android 4.0.4 tablet (API 15). The only issue I have noticed so far is that there is some lag when starting a video using the build in video player. The sound starts first, and after a few seconds the picture/video is shown. Same happens if I skip to another place in the video. Maybe the VLC player is a bit to demanding for my tablet, Samsung Galaxy P7320 (same as P7300 but with LTE/4G).
> 
> That's my issue as well. VLC is too heavy for my device. MX Player works good on it. @sh000gun Can you update it to MX Player in any way? The HD Streams load at least but I only hear the sound. The picture doesn't react and is lagging :/ . Thank you for the effort so far!!

To be clear, I use libvlc library to integrate into Newpipe. MX Player is closed source so I cannot do anything

**Comment by malekairmaroc7** [comment]
Oh I see. Damn thats too bad. Thought MX Player is open source.

**Comment by tbjorheim** [comment]
@sh000gun Your fork has stopped working due to recently Youtube changes. Can you please sync it with the latest changes to make it up to date with version 19.8? Thanks.

**Comment by Kovaelin** [comment]
Good to see there's still work being done for 4.0.X. Thanks.

I don't know what's going on, but even on non-legacy, there are some times when the app just won't load and then it'll just work again later.

**Comment by sh000gun** [comment]
> @sh000gun Your fork has stopped working due to recently Youtube changes. Can you please sync it with the latest changes to make it up to date with version 19.8? Thanks.

It still works now. Can you check it again?

**Comment by tbjorheim** [comment]
Yes, you are right. It's still works. :)  Many Youtube addons (Kodi, Squeezebox and Newpipe) stopped working when Youtube did some changes a while back. And since there was an update for the normal Newpipe, I also assumed this was needed to fix the problem.

But as long as it's working again now, everything is okay. :)

Thanks for your feedback.

**Comment by Sash0k** [comment]
@sh000gun trying to use your fork, unfortunately got some issues.
tablet info:

```json
{
	"user_action": "ui error",
	"request": "App crash, UI failure",
	"content_language": "ru_RU",
	"service": "none",
	"package": "org.schabi.newpipelegacy",
	"version": "0.19.5",
	"os": "Linux Android 4.0.3 - 15",
}
```

- vertical screen orientation on playback (on tablet)
- playback crash

```
android.content.res.Resources$NotFoundException: File res/drawable/ic_fast_rewind_white_24dp.xml from drawable resource ID #0x7f0800e5. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
at android.content.res.Resources.loadDrawable(Resources.java:1925)
at android.content.res.Resources.getDrawable(Resources.java:664)
at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:470)
at org.schabi.newpipelegacy.player.VideoPlayer.showAndAnimateControl(VideoPlayer.java:1015)
at org.schabi.newpipelegacy.player.VideoPlayer.onFastRewind(VideoPlayer.java:780)
at org.schabi.newpipelegacy.player.PopupVideoPlayer$PopupWindowGestureListener.onDoubleTap(PopupVideoPlayer.java:895)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:497)
at org.schabi.newpipelegacy.player.PopupVideoPlayer$PopupWindowGestureListener.onTouch(PopupVideoPlayer.java:1020)
...
at dalvik.system.NativeStart.main(Native Method)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:863)
at android.graphics.drawable.Drawable.createFromXml(Drawable.java:804)
at android.content.res.Resources.loadDrawable(Resources.java:1922)
```
- downloading crash

```
java.lang.NoSuchMethodError: android.net.ConnectivityManager.isActiveNetworkMetered
at us.shandian.giga.service.DownloadManagerService.handleConnectivityState(DownloadManagerService.java:322)
at us.shandian.giga.service.DownloadManagerService.access$000(DownloadManagerService.java:56)
at us.shandian.giga.service.DownloadManagerService$2.onReceive(DownloadManagerService.java:180)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:728)
at android.os.Handler.handleCallback(Handler.java:605)
...
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by sh000gun** [comment]
> @sh000gun trying to use your fork, unfortunately got some issues.
> tablet info:
> 
> ```json
> {
> 	"user_action": "ui error",
> 	"request": "App crash, UI failure",
> 	"content_language": "ru_RU",
> 	"service": "none",
> 	"package": "org.schabi.newpipelegacy",
> 	"version": "0.19.5",
> 	"os": "Linux Android 4.0.3 - 15",
> }
> ```
> 
> * vertical screen orientation on playback (on tablet)
> * playback crash
> 
> ```
> android.content.res.Resources$NotFoundException: File res/drawable/ic_fast_rewind_white_24dp.xml from drawable resource ID #0x7f0800e5. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
> at android.content.res.Resources.loadDrawable(Resources.java:1925)
> at android.content.res.Resources.getDrawable(Resources.java:664)
> at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:470)
> at org.schabi.newpipelegacy.player.VideoPlayer.showAndAnimateControl(VideoPlayer.java:1015)
> at org.schabi.newpipelegacy.player.VideoPlayer.onFastRewind(VideoPlayer.java:780)
> at org.schabi.newpipelegacy.player.PopupVideoPlayer$PopupWindowGestureListener.onDoubleTap(PopupVideoPlayer.java:895)
> at android.view.GestureDetector.onTouchEvent(GestureDetector.java:497)
> at org.schabi.newpipelegacy.player.PopupVideoPlayer$PopupWindowGestureListener.onTouch(PopupVideoPlayer.java:1020)
> ...
> at dalvik.system.NativeStart.main(Native Method)
> Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
> at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:863)
> at android.graphics.drawable.Drawable.createFromXml(Drawable.java:804)
> at android.content.res.Resources.loadDrawable(Resources.java:1922)
> ```
> 
> * downloading crash
> 
> ```
> java.lang.NoSuchMethodError: android.net.ConnectivityManager.isActiveNetworkMetered
> at us.shandian.giga.service.DownloadManagerService.handleConnectivityState(DownloadManagerService.java:322)
> at us.shandian.giga.service.DownloadManagerService.access$000(DownloadManagerService.java:56)
> at us.shandian.giga.service.DownloadManagerService$2.onReceive(DownloadManagerService.java:180)
> at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:728)
> at android.os.Handler.handleCallback(Handler.java:605)
> ...
> at dalvik.system.NativeStart.main(Native Method)
> ```

Thanks. I will try to fix it

**Comment by sh000gun** [comment]
> @sh000gun trying to use your fork, unfortunately got some issues.
> tablet info:
> 
> ```json
> {
> 	"user_action": "ui error",
> 	"request": "App crash, UI failure",
> 	"content_language": "ru_RU",
> 	"service": "none",
> 	"package": "org.schabi.newpipelegacy",
> 	"version": "0.19.5",
> 	"os": "Linux Android 4.0.3 - 15",
> }
> ```
> 
> * vertical screen orientation on playback (on tablet)
> * playback crash
> 
> ```
> android.content.res.Resources$NotFoundException: File res/drawable/ic_fast_rewind_white_24dp.xml from drawable resource ID #0x7f0800e5. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
> at android.content.res.Resources.loadDrawable(Resources.java:1925)
> at android.content.res.Resources.getDrawable(Resources.java:664)
> at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:470)
> at org.schabi.newpipelegacy.player.VideoPlayer.showAndAnimateControl(VideoPlayer.java:1015)
> at org.schabi.newpipelegacy.player.VideoPlayer.onFastRewind(VideoPlayer.java:780)
> at org.schabi.newpipelegacy.player.PopupVideoPlayer$PopupWindowGestureListener.onDoubleTap(PopupVideoPlayer.java:895)
> at android.view.GestureDetector.onTouchEvent(GestureDetector.java:497)
> at org.schabi.newpipelegacy.player.PopupVideoPlayer$PopupWindowGestureListener.onTouch(PopupVideoPlayer.java:1020)
> ...
> at dalvik.system.NativeStart.main(Native Method)
> Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
> at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:863)
> at android.graphics.drawable.Drawable.createFromXml(Drawable.java:804)
> at android.content.res.Resources.loadDrawable(Resources.java:1922)
> ```
> 
> * downloading crash
> 
> ```
> java.lang.NoSuchMethodError: android.net.ConnectivityManager.isActiveNetworkMetered
> at us.shandian.giga.service.DownloadManagerService.handleConnectivityState(DownloadManagerService.java:322)
> at us.shandian.giga.service.DownloadManagerService.access$000(DownloadManagerService.java:56)
> at us.shandian.giga.service.DownloadManagerService$2.onReceive(DownloadManagerService.java:180)
> at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:728)
> at android.os.Handler.handleCallback(Handler.java:605)
> ...
> at dalvik.system.NativeStart.main(Native Method)
> ```

@Sash0k I fixed them.

**Comment by Sash0k** [comment]
good work!
i've test a bit. playback is working, but downloading crashes

> android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=video/mp4 flg=0x43 (has extras) }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1512)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1384)
at android.app.Activity.startActivityForResult(Activity.java:3217)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:236)
at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1278)
at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1266)
at us.shandian.giga.io.StoredFileHelper.requestSafWithFileCreation(StoredFileHelper.java:153)
at org.schabi.newpipelegacy.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:646)
at org.schabi.newpipelegacy.download.DownloadDialog.lambda$initToolbar$4$DownloadDialog(DownloadDialog.java:411)
at org.schabi.newpipelegacy.download.-$$Lambda$DownloadDialog$wt4L8_SGYsEZuScE_xl-I_tfM5c.onMenuItemClick(lambda)
at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)

**Comment by wb9688** [comment]
@Sash0k: What? Have you enabled SAF in the settings? SAF shouldn't be enableable on Android 4, as well, that doesn't work and thus causes a crash.

**Comment by tbjorheim** [comment]
@sh000gun It seems your fork has stopped working due to recent Youtube changes. Is it possible to fix it? It's not necessary to bring it up to date with latest Newpipe, but at least fixing the extractor so it will start working again would be great. Thanks. :)

**Comment by bluerex11178** [comment]
@sh000gun your latest version doesn't seem to be working could not parse website
I have a lg e400 with cm9

**Comment by sh000gun** [comment]
@tbjorheim @bluerex11178 Thanks for your info. I fixed it with latest Extractor and hope it works well for you guys. Just go to my release page and test.

**Comment by ShareASmile** [comment]
@sh000gun  Thank you very much for the effort you've done! I Can you Link me to Latest Apk as Release Page of your fork still showing june 23 apk which stopped working some days ago.

**Comment by sh000gun** [comment]
> @sh000gun Thank you very much for the effort you've done!
> 
> Can you Link me to Latest Apk as Release Page of your fork still showing june 26 old apk as latest release which stopped working some days ago. btw i just checked
> https://github.com/sh000gun/NewPipe-legacy/releases

Hi,
Apk is latest build with my fix so you can check

**Comment by bluerex11178** [comment]
@sh000gun the newest version just crashes immediately 
lg e400 cm9

**Comment by tbjorheim** [comment]
@sh000gun Thank you for providing a new update at https://github.com/sh000gun/NewPipe-legacy/releases

But the latest update crashes on startup on my Samsung Galaxy P7320, Android 4.0.4 (API 15).

Is it possible to fix this? Here is the output from logcat:

> E/dalvikvm(12718): Could not find class 'android.app.NotificationChannel', referenced from method org.schabi.newpipelegacy.App.setUpUpdateNotificationChannel
W/dalvikvm(12718): VFY: unable to resolve new-instance 50 (Landroid/app/NotificationChannel;) in Lorg/schabi/newpipelegacy/App;
E/dalvikvm(12718): Could not find class 'android.app.NotificationChannel', referenced from method org.schabi.newpipelegacy.App.initNotificationChannel
W/dalvikvm(12718): VFY: unable to resolve new-instance 50 (Landroid/app/NotificationChannel;) in Lorg/schabi/newpipelegacy/App;
W/dalvikvm(12718): VFY: unable to resolve virtual method 508: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(12718): VFY: unable to resolve virtual method 37023: Lorg/acra/collections/ImmutableSet;.iterator ()Ljava/util/Iterator;
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(12718): VFY: unable to resolve virtual method 37023: Lorg/acra/collections/ImmutableSet;.iterator ()Ljava/util/Iterator;
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
E/dalvikvm(12718): Could not find class 'org.acra.collections.ImmutableList', referenced from method org.acra.config.CoreConfiguration.<init>
W/dalvikvm(12718): VFY: unable to resolve new-instance 5449 (Lorg/acra/collections/ImmutableList;) in Lorg/acra/config/CoreConfiguration;
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(12718): threadid=1: thread exiting with uncaught exception (group=0x40c231f8)
E/AndroidRuntime(12718): FATAL EXCEPTION: main
E/AndroidRuntime(12718): java.lang.NoClassDefFoundError: org.acra.collections.ImmutableList
E/AndroidRuntime(12718): 	at org.acra.config.CoreConfiguration.<init>(CoreConfiguration.java:118)
E/AndroidRuntime(12718): 	at org.acra.config.CoreConfigurationBuilder.build(CoreConfigurationBuilder.java:835)
E/AndroidRuntime(12718): 	at org.schabi.newpipelegacy.App.initACRA(App.java:210)
E/AndroidRuntime(12718): 	at org.schabi.newpipelegacy.App.attachBaseContext(App.java:83)
E/AndroidRuntime(12718): 	at android.app.Application.attach(Application.java:154)
E/AndroidRuntime(12718): 	at android.app.Instrumentation.newApplication(Instrumentation.java:961)
E/AndroidRuntime(12718): 	at android.app.Instrumentation.newApplication(Instrumentation.java:945)
E/AndroidRuntime(12718): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:477)
E/AndroidRuntime(12718): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3950)
E/AndroidRuntime(12718): 	at android.app.ActivityThread.access$1300(ActivityThread.java:127)
E/AndroidRuntime(12718): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
E/AndroidRuntime(12718): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12718): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(12718): 	at android.app.ActivityThread.main(ActivityThread.java:4519)
E/AndroidRuntime(12718): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12718): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(12718): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
E/AndroidRuntime(12718): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
E/AndroidRuntime(12718): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Liaam24** [comment]
I have a tablet Lenovo on Android 4.0.4 and download the **v0.19.5-libvlc-min-api-14** and works but with some  errors

**Comment by nydas3k** [comment]
@sh000gun any new updates? the new version is crashing...

**Comment by the-r3dacted** [comment]
I'm curious to see if it would be possible to get Android 2.3 support. Although I'm not sure if it would be worth the effort.

**Comment by ShareASmile** [comment]
See Developer's Comment
https://github.com/TeamNewPipe/NewPipe-legacy/issues/75#issuecomment-861303146
